config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :contacts
  root 'home#index'
  get 'home/list'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[show edit update destroy]

  # GET /contacts or /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1 or /contacts/1.json
  def show; end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit; end

  # POST /contacts or /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1 or /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1 or /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_contact
    @contact = Contact.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def contact_params
    params.require(:contact).permit(:last_name, :first_name, :state, :city, :zip_code, :phone, :email)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end

  def list; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contacts/_form.html.erb
<%= form_with(model: contact) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> Prohibited this contact from being saved:</h2>

      <ul>
        <% contact.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <h2>Name</h2>

  <div class="field">
    <strong>Last:</strong>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <strong>First:</strong>
    <%= form.text_field :first_name %>
  </div>

<h2>Address</h2>

  <div class="field">
    <strong>State:</strong>
    <%= form.text_field :state %>
  </div>

  <div class="field">
    <strong>City:</strong>
    <%= form.text_field :city %>
  </div>

  <div class="field" style="margin-bottom: 20px">
    <strong>Zip:</strong>
    <%= form.number_field :zip_code %>
  </div>

  <div class="field">
    <strong>Phone:</strong>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <strong>Email:</strong>
    <%= form.text_field :email %>
  </div>

  <div class="actions" style="margin-top: 20px">
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h2>Editing Contact</h2>

<%= render 'form', contact: @contact %>
<br/>
<%= link_to 'Show', @contact %> |
<%= link_to 'List', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th colspan="2" bgcolor="yellow">Name</th>
      <th></th>
      <th colspan="3" bgcolor="cyan">Address</th>
    </tr>
    <tr style="background: #bbb">
      <th>Last</th>
      <th>First</th>
      <th></th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th></th>
      <th>Phone#</th>
      <th>Email</th>
      <th colspan="3" style="background: #fff"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.order(:last_name).each do |contact| %>
      <tr>
        <td><%= contact.last_name %></td>
        <td><%= contact.first_name %></td>
        <td></td>
        <td><%= contact.city %></td>
        <td><%= contact.state %></td>
        <td><%= contact.zip_code %></td>
        <td></td>
        <td><%= contact.phone %></td>
        <td><%= contact.email %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Delete', contact, :method => :delete, data: {confirm: "Are you sure?"} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p style="font-family: Arial; font-size: 20px;">
  <%= @contact.last_name %>, 
  <%= @contact.first_name %>
</p>

<p>
  <%= @contact.city %>, 
  <%= @contact.state %>
  <%= @contact.zip_code %>
</p>

<p style="margin: 24px;">
  <div>
    <strong style="color: purple;">Phone:</strong>
    <%= @contact.phone %>
  </div>
  <div>
    <strong style="color: blue;">Email:</strong>
    <%= @contact.email %>
  </div>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'List', contacts_path %>

app/views/home/_header.html.erb
<h2 id="headLogo">Web-based Address Book for Breeze</h2>
    <div class="links_line">
      <div class="nav-link">
        <a href="index.html">Home</a>
      </div>
      <div class="nav-link">
        <a href="Login.html">Login</a>
      </div>
      <div class="nav-link">
        <a href="List.html">List</a>
      </div>
      <div class="nav-link">
        <a href="Search.html">Search</a>
      </div>
    </div>

app/views/home/index.html.erb
<img style="padding: 5%" src="/Images/BreezeLogo.svg">
<p>
The purpose of this project is to assist Breeze Airways with assessing your
knowledge and competency with Ruby on Rails. In order to complete the
project, you will need to have a basic knowledge of Rails, HTML, and CSS.
Requirements
The project is to develop a web-based address book with a minimum set of
features. You will need to use git and Github.com as your repository. Please
ensure the first commit is a blank Rails project so Breeze can review all
subsequent commits.
</p>
<strong>Basic requirements:</strong>
<br/>• PostgreSQL as the database technology
<br/>• Ability to add, edit, and delete contacts
<br/>• Contacts should have a minimum set of fields:
<br/>§ Name
<br/>§ Address
<br/>§ Email
<br/>§ Phone
<br/>• Ability to view all contacts in a list sorted alphabetically by name
<br/>• Host the app on a free Heroku.com account
<p>
Feel Free to expand on the basic requirements with extra features such as user
authentication.
Once completed send the links to your Github.com repository and the app
hosted on Heroku.com to dee.evans@flybreeze.com
</p>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <p class="notice"><%=notice %></p>

  </head>
  <body>

    <%= render "/header" %>

    <div class="page">
      <br/>
      <%= yield %>
    </div>

  </body>
</html>

app/views/tbl_addrs/_form.html.erb
<%= form_with(model: tbl_addr) do |form| %>
  <% if tbl_addr.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tbl_addr.errors.count, "error") %> prohibited this tbl_addr from being saved:</h2>

      <ul>
        <% tbl_addr.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :zip %>
    <%= form.number_field :zip %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>